CREATE TABLE news (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  header VARCHAR(250) NOT NULL,
  content VARCHAR(10000) NOT NULL
);

INSERT INTO news (header, content) VALUES
  ('FIRST HEADER', 'Solum vituperata definitiones te vis, vis alia falli doming ea. Vivendum dignissim conceptam pri ut, ei vel partem audiam sapientem. Nisl omittam complectitur pro an, quem omnes munere id vix. Lorem ipsum dolor sit amet, an eos lorem ancillae expetenda, vim et utamur quaestio. Ius dicat feugiat no, vix cu modo dicat principes. Magna copiosae apeirian ius at. Solum vituperata definitiones te vis, vis alia falli doming ea. An eos iusto solet, id mel dico habemus. '),
  ('SECOND HEADER', 'Nec labore cetero theophrastus no, ei vero facer veritus nec. Oratio accumsan et mea. Tation delenit percipitur at vix. Lorem ipsum dolor sit amet, an eos lorem ancillae expetenda, vim et utamur quaestio. Vel in dicant cetero phaedrum, usu populo interesset cu, eum ea facer nostrum pericula.    Sea esse deserunt ei, no diam ubique euripidis has. Elitr accommodare deterruisset eam te, vim munere pertinax consetetur at. Sea esse deserunt ei.'),
  ('THIRD HEADER', 'Vel in dicant cetero phaedrum, usu populo interesset cu, eum ea facer nostrum pericula. Eu cum iuvaret debitis voluptatibus, esse perfecto reformidans id has.                  Eu eam dolores lobortis percipitur, quo te equidem deleniti disputando. Vel in dicant cetero phaedrum, usu populo interesset cu, eum ea facer nostrum pericula.    . Postulant assueverit ea his.'),
  ('FOURTH HEADER', 'Itaque earum rerum hic tenetur a sapiente delectus, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, ut et voluptates repudiandae sint et molestiae non recusandae.'),
  ('FIFTH HEADER', 'Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet, quis nostrum exercitationem ullam corporis suscipit laboriosam, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis, qui blanditiis praesentium voluptatum deleniti atque corrupti, quos dolores et quas molestias excepturi sint, ut et voluptates repudiandae sint et molestiae non recusandae? Excepteur sint occaecat cupidatat non proident, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, ut et voluptates repudiandae sint et molestiae non recusandae? Itaque earum rerum hic tenetur a sapiente delectus, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat? Ut enim ad minima veniam, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.');